### ISSUE TITLE
More like this bigger modal

### ISSUE THREAD

**Issue by alexlepinski** [osu-cass/SampleItemsWebsite#119]
On a normal screen it shows 2 rows. make the modal wider

**Comment by alexlepinski** [comment]
might be fixed. see dup#115

**Comment by EvanSchallerer** [comment]
Please verify on a smaller screen size, this should be resolved.

**Comment by EvanSchallerer** [comment]
@alexlepinski not an issue. Please reopen if you can reproduce.
