### ISSUE TITLE
Loading spinner never stops

### ISSUE THREAD

**Issue by EvanSchallerer** [osu-cass/SampleItemsWebsite#160]
- Go to an item
- Click "Accessibility"
- Reset to default
- Click "Accessibility"
- Update

Loading spinner starts but does not go away

**Comment by RikkiGibson** [comment]
Can you check if ItemFrame implements `componentWillReceiveProps` in the version you were testing with? We deleted that because of something that sounds very similar to this.

**Comment by EvanSchallerer** [comment]
I found that issue on dev which does not implement that. The issue also occurs on master.

**Comment by EvanSchallerer** [comment]
Verified in branch feature_disable-calculator.

**Comment by bmikkelsen22** [comment]
Fixed in feature_disable-calculator

**Comment by alexlepinski** [comment]
+1
