### ISSUE TITLE
Remove specified accessibility options

### ISSUE THREAD

**Issue by EvanSchallerer** [osu-cass/SampleItemsWebsite#162]
Remove the following for all items. Disable in accessibility config.
- Mark for review
- Item Tools
- TTS
- Print on Demand
- Illustration Glossary

**Comment by alexlepinski** [comment]
Writing tools is mislabeled in the xml. This is the item menu toolbar. Do we want to display item toolbar whenever possible?

**Comment by bmikkelsen22** [comment]
-1 Mark for review not removed in feature_disable-calculator
+1 Item Tools removed in feature_disable-calculator
+1 TTS removed, message displayed in feature_disable-calculator
+1 Print on demand removed? (Not in Accessibility)
+1 Illustration Glossary removed in feature_disable-calculator

**Comment by alexlepinski** [comment]
+1
