### ISSUE TITLE
"More" collapsible element changes

### ISSUE THREAD

**Issue by EvanSchallerer** [osu-cass/SampleItemsWebsite#170]
- Move search by id box out of collapsible element on search page
- Remove "More" collapsible box

**Comment by EvanSchallerer** [comment]
Verified in branch feature_remove-calculator.

**Comment by bmikkelsen22** [comment]
+1 Complete in branch feature_disable-calculator, does not allow collapsing

**Comment by alexlepinski** [comment]
Add collapsible back

**Comment by EvanSchallerer** [comment]
Completed in stage.
