### ISSUE TITLE
Change "Search" naming

### ISSUE THREAD

**Issue by EvanSchallerer** [osu-cass/SampleItemsWebsite#171]
- Do not refer to the search feature as "search", instead use "Browse"
    - Fix in routing
    - Fix in navigation bar
    - Fix in H1 tag

**Comment by EvanSchallerer** [comment]
Verified in branch feature_remove-calculator.

**Comment by bmikkelsen22** [comment]
+1 Fix in routing
-1 not changed in navigation bar 
+1 Fixed in H1 tag

**Comment by bmikkelsen22** [comment]
+1 Fixed in feature_disable-calculator

**Comment by alexlepinski** [comment]
Navigation bar should only have "Browse Test Items" no icon

**Comment by EvanSchallerer** [comment]
Fixed in dev, closing.
