### ISSUE TITLE
Calculator enabled only for allowcalculator flag

### ISSUE THREAD

**Issue by EvanSchallerer** [osu-cass/SampleItemsWebsite#176]

**Comment by EvanSchallerer** [comment]
Verified in branch feature_disable-calculator.

**Comment by bmikkelsen22** [comment]
+1 fixed in feature_disable-calculator

**Comment by EvanSchallerer** [comment]
Logic changed to only allow calculator when allowcalculator = Y and it is not disabled by the accessibility config. Fixed in dev, closing.
