### ISSUE TITLE
R#37 Listening play/pause Research

### ISSUE THREAD

**Issue by alexlepinski** [osu-cass/SampleItemsWebsite#182]

**Comment by Garrett-S** [comment]
There are several different audio widgets in the "Audio2" ui scripts. Currently the "createPlayer" widget is being used. The "createPlayerRewindWidget provides a play/pause button, and a rewind to start button which is closer to what we want.

**Comment by Garrett-S** [comment]
Upon further investigation there is an undocumented code for the audio options. This controls which buttons are displayed. The "TDS_APC_SCRUBBER" code enables audio with a progress bar and play/pause buttons.
