### ISSUE TITLE
Thesaurus should be part of dictionary for ELA writing questions

### ISSUE THREAD

**Issue by struthj** [osu-cass/SampleItemsWebsite#185]
Issue "Should be part of the dictionary that is available on ELA full writes. Did not fins this tool anywhere."
"Notes: Will Investigate using the UCLA dictionary host to correct the problem."

**Comment by alexlepinski** [comment]
references 03,11, +1

**Comment by EvanSchallerer** [comment]
@alexlepinski please review, this does not appear to be working in stage
