### ISSUE TITLE
Dictionary by grades

### ISSUE THREAD

**Issue by alexlepinski** [osu-cass/SampleItemsWebsite#202]
Update the accessibility config

(Grades 3-5) ("Student 2" or "sd2")
(Grades 6-8) ("Student 3" or "sd3")
(Grades 9-11) ("Student 4" or "sd4")

**Comment by struthj** [comment]
fixed with https://github.com/osu-cass/AccessibilityAccommodationConfigurations/commit/29d405fbdee2227ad16ccac150c19bb03184949d
