### ISSUE TITLE
Share accessibility bug 

### ISSUE THREAD

**Issue by alexlepinski** [osu-cass/SampleItemsWebsite#207]
Share accessibility doesn't select the right code for Translations (Glossaries). I believe it is because of the duplicate codes for English glossary and Translations

1. Open math item 1432 or any math
2. Select Accessibility modal
3. Select reset to default
4. Select Accessibility modal
5. Change Translations (Glossaries) to Spanish
6. Select Save
7. Select Share
8. Copy and paste url in new window
9. Open Accessibility modal
10. Translations (Glossaries) shows default option should be Spanish

**Comment by Garrett-S** [comment]
This appears to be fixed in milestone-3
