### ISSUE TITLE
Braille link

### ISSUE THREAD

**Issue by alexlepinski** [osu-cass/SampleItemsWebsite#223]
List a link above the iframe that downloads an file not preview

Link label "Download Braille Embossing"

add icon for download

**Comment by struthj** [comment]
@846981702780ed762667c98e4cfef8099a14a31a added the glyphicon-download-alt
I can change the styling around if it doesn't look right

**Comment by Garrett-S** [comment]
The link needs to have a loading icon because it takes us a few seconds to fetch, zip and serve the braille files.

**Comment by Garrett-S** [comment]
Loading icon added in @164282abab0efd77982d2dc780ad4dc0e42511c6
