### ISSUE TITLE
Navigate to PT item selected

### ISSUE THREAD

**Issue by alexlepinski** [osu-cass/SampleItemsWebsite#236]
Change order to be default by sequence number

IVS needs to focus on id passed in

**Comment by Garrett-S** [comment]
We need to:
- [ ] Track what ID was passed in first
- [ ] Sort by ID
- [ ] Focus on passed in ID

What about in streamlined mode? Focusing on the item will cause it to scroll past the passage.

**Comment by alexlepinski** [comment]
completed
