### ISSUE TITLE
Braille swap items

### ISSUE THREAD

**Issue by alexlepinski** [osu-cass/SampleItemsWebsite#248]
Render braille item in placement of non-braille item.

- [x] Add to config/patch if can't find in metadata
- [x] Filter search page to only view non-braille-only items
- [x] Load braille accessibility from braille-only item if exists
- [x] Swap braille item if braille is selected client only
- [x] Download braille based on braille enabled items (swap out items for braille enabled)

**Comment by alexlepinski** [comment]
Needs UAT

**Comment by struthj** [comment]
@alexlepinski slacked you the UAT for this.

**Comment by alexlepinski** [comment]
completed
